### ISSUE TITLE
[PE-D][Tester D] Programme's internal management of state is buggy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T15-4/tp#197] opened 2023-03-31 19:35 UTC
I was in the Course Page but the programme thought I was still in the Student Page. 

![image.png](https://raw.githubusercontent.com/unfazing/ped/main/files/5a823c3d-562e-41eb-aee2-4d5849b724ef.png)

- observe the `add course` command returns an error in above screenshot

![image.png](https://raw.githubusercontent.com/unfazing/ped/main/files/3f372017-3dba-4e1f-a7ed-924f36883302.png)

- observe the `help` command returns the help info for Student page.

This bug occurred while I was testing the `find course` command on the Course Page. 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: unfazing/ped#8

**Comment by tyx021** [comment] 2023-04-01 04:51
I'm unable to reproduce this bug, can anyone try it?

**Comment by swxk19** [comment] 2023-04-01 04:58
I'm unable to reproduce it too. I've implemented

**Comment by swxk19** [comment] 2023-04-01 05:10
If it's not a UI issue but rather a logical issue, then will have to dig where page CurrentSelection.currentPage is not being updated correctly.

**Comment by tyx021** [comment] 2023-04-04 09:22
Seems like this was fixed #215 , close it for now.

**Closed by tyx021** 2023-04-04 09:22 UTC
Labels: type.Bug, priority.High, severity.High, PE-D
